# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  Account.create!([{company: 'printonrails'}])
  AdminUser.create!([{email: 'info@printonrails.com', password: 'password', password_confirmation: 'password', role:'super_admin', first: 'Daniel', last: 'Hatcher', account_id: 1}])
  AdminUser.create!([{email: 'admin@printonrails.com', password: 'password', password_confirmation: 'password', role:'admin', first: 'admin', last: 'admin'}])
  AdminUser.create!([{email: 'office@printonrails.com', password: 'password', password_confirmation: 'password', role:'office', first: 'office', last: 'office'}])
  AdminUser.create!([{email: 'warehouse@printonrails.com', password: 'password', password_confirmation: 'password', role:'warehouse', first: 'warehouse', last: 'warehouse'}])
  AdminUser.create!([{email: 'broker@printonrails.com', password: 'password', password_confirmation: 'password', role:'broker', first: 'broker', last: 'broker'}])
  OrderCategory.create!([{name: 'screen_print'}])
  OrderCategory.create!([{name: 'embroidery'}])
  OrderStatus.create!([{name: 'new'}])
  OrderStatus.create!([{name: 'approved', active: 'true'}])
  OrderStatus.create!([{name: 'complete', active: 'false'}])
  OrderStatus.create!([{name: 'hold', active: 'false'}])
  OrderStatus.create!([{name: 'cancelled', active: 'false'}])
  ArtStatus.create!([{name: 'in_progress'}])
  ArtStatus.create!([{name: 'complete'}])
  ProductStatus.create!([{name: 'buy_product'}])
  ProductStatus.create!([{name: 'purchased'}])
  ProductStatus.create!([{name: 'partial'}])
  ProductStatus.create!([{name: 'complete'}])
  OrderType.create!([{name: 'new'}])
  OrderType.create!([{name: 'repeat order'}])
  PrintLocation.create!([{name: 'front'}])
  PrintLocation.create!([{name: 'back'}])
  PrintLocation.create!([{name: 'chest(L)'}])
  PrintLocation.create!([{name: 'chest(R)'}])
  PrintLocation.create!([{name: 'sleeve(L)'}])
  PrintLocation.create!([{name: 'sleeve(R)'}])
  PrintLocation.create!([{name: 'leg(L)'}])
  PrintLocation.create!([{name: 'leg(R)'}])
  PrintLocation.create!([{name: 'hat(front)'}])
  PrintLocation.create!([{name: 'hat(back)'}])
