# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  Account.create!([{company: 'printonrails'}])
  AdminUser.create!([{email: 'info@printonrails.com', password: 'password', password_confirmation: 'password', role:'super_admin', first: 'Daniel', last: 'Hatcher', account_id: 1}])
  Account.create!([{company: 'demo'}])
  AdminUser.create!([{email: 'test@example.com', password: 'password', password_confirmation: 'password', role:'account_admin', first: 'test', last: 'test', account_id: 2}])
  AdminUser.create!([{email: 'example@demo.com', password: 'password', password_confirmation: 'password', role:'demo', first: 'demo', last: 'demo', account_id: 2}])
  OrderCategory.create!([{name: 'screen_print'}])
  OrderCategory.create!([{name: 'embroidery'}])
  # OrderStatus.create!([{name: 'new'}])
  # OrderStatus.create!([{name: 'approved', active: 'true'}])
  # OrderStatus.create!([{name: 'complete', active: 'false'}])
  # OrderStatus.create!([{name: 'hold', active: 'false'}])
  # OrderStatus.create!([{name: 'cancelled', active: 'false'}])
  # ArtStatus.create!([{name: 'in_progress'}])
  # ArtStatus.create!([{name: 'complete'}])
  # ProductStatus.create!([{name: 'buy_product'}])
  # ProductStatus.create!([{name: 'purchased'}])
  # ProductStatus.create!([{name: 'partial'}])
  # ProductStatus.create!([{name: 'complete'}])
  OrderType.create!([{name: 'new'}])
  OrderType.create!([{name: 'repeat order'}])
  Location.create!([{name: 'front'}])
  Location.create!([{name: 'back'}])
  Location.create!([{name: 'chest(L)'}])
  Location.create!([{name: 'chest(R)'}])
  Location.create!([{name: 'sleeve(L)'}])
  Location.create!([{name: 'sleeve(R)'}])
  Location.create!([{name: 'pocket(L)'}])
  Location.create!([{name: 'pocket(R)'}])
  Location.create!([{name: 'leg(L)'}])
  Location.create!([{name: 'leg(R)'}])
  Location.create!([{name: 'hat(front)'}])
  Location.create!([{name: 'hat(back)'}])
