# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  AdminUser.create!([{email: 'info@printonrails.com', password: 'password', password_confirmation: 'password', role:'super_admin', first: 'Daniel', last: 'Hatcher'}])
  OrderCategory.create!([{name: 'screen print'}])
  OrderCategory.create!([{name: 'embroidery'}])
  OrderStatus.create!([{name: 'new'}])
  OrderStatus.create!([{name: 'approved', active: 'true'}])
  OrderStatus.create!([{name: 'art in progress', active: 'true'}])
  OrderStatus.create!([{name: 'setup in progress', active: 'true'}])
  OrderStatus.create!([{name: 'print in progress', active: 'true'}])
  OrderStatus.create!([{name: 'complete', active: 'false'}])
  OrderStatus.create!([{name: 'hold', active: 'false'}])
  OrderStatus.create!([{name: 'cancelled', active: 'false'}])
  ProductStatus.create!([{name: 'please order!'}])
  ProductStatus.create!([{name: 'ordered'}])
  ProductStatus.create!([{name: 'partial'}])
  ProductStatus.create!([{name: 'complete'}])
  OrderType.create!([{name: 'new'}])
  OrderType.create!([{name: 'repeat order'}])
  PrintLocation.create!([{name: 'front'}])
  PrintLocation.create!([{name: 'back'}])
  PrintLocation.create!([{name: 'chest(L)'}])
  PrintLocation.create!([{name: 'chest(R)'}])
  PrintLocation.create!([{name: 'sleeve(L)'}])
  PrintLocation.create!([{name: 'sleeve(R)'}])
  PrintLocation.create!([{name: 'leg(L)'}])
  PrintLocation.create!([{name: 'leg(R)'}])
  PrintLocation.create!([{name: 'hat(front)'}])
  PrintLocation.create!([{name: 'hat(back)'}])
